config/routes.rb
Rails.application.routes.draw do
  # resources :transactions
  devise_for :users
  resources :articles do
    member do
      post 'like'
      delete 'unlike'
    end
  end

  resources :articles do
    resources :comments
    resources :transactions
  end

  namespace :api do
    namespace :v1 do
      delete '/articles/deleteAll', to: 'articles#deleteAll'
      resources :articles, only: [:destroy]
    end
  end

  resources :users do
    member { patch 'incr_balance' }
    member { patch 'decr_balance' }
    member { delete 'destroy_user'}
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :transactions, dependent: :destroy
end

app/controllers/api/v1/articles_controller.rb
# app/controllers/api/v1/articles_controller.rb
module Api
  module V1
    class ArticlesController < ApplicationController
      skip_before_action :verify_authenticity_token

      def destroy
        @article = Article.find(params[:id])
        if @article.destroy
          render json: { status: 'SUCCESS', message: 'Deleted article', data: @article }, status: :ok
        else
          render json: { status: 'ERROR', message: 'Article not deleted', data: @article.errors }, status: :unprocessable_entity
        end
      end

      def deleteAll
        begin
          Article.transaction do
            Article.find_each(&:destroy!)
          end
          render json: { status: 'SUCCESS', message: 'Deleted all articles' }, status: :ok
        rescue => e
          render json: { status: 'ERROR', message: 'Failed to delete all articles', data: e.message }, status: :unprocessable_entity
        end
      end
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  def like
    @article = Article.find(params[:id])
    @like = current_user.likes.build(article_id: params[:id])
    @author = @article.user;

    ActiveRecord::Base.transaction do
      if @like.save
        @author.update(balance: @author.balance + 1)
        redirect_to @article, notice: 'You liked this article!'
      else
        redirect_to @article, notice: 'Error liking post.'
        raise ActiveRecord::Rollback
      end
    end

  end

  def unlike
    @article = Article.find(params[:id])
    @like = current_user.likes.find_by(article_id: params[:id])
    @author = @article.user

    ActiveRecord::Base.transaction do
      @like.destroy if @like
      @author.update(balance: @author.balance - 1)
      redirect_to @article, notice: 'You unliked this article!'
    end
  end

  # GET /articles or /articles.json
  def index
    if params[:sort].present?
      session[:sort] = params[:sort]
    elsif !session[:sort].present?
      session[:sort] = 'likes'
    end
    @articles = case session[:sort]
    when 'likes'
      Article.includes(comments: :user).order(likes_count: :desc).page(params[:page])
    when 'latest'
      Article.includes(comments: :user).order(created_at: :desc).page(params[:page])
    else
      Article.includes(comments: :user).all.page(params[:page]) #shouldn't happen, but just in case
    end
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.includes(:user)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    params[:article][:user_id] = current_user.id if params[:article][:user_id].nil?
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      params[:article][:user_id] = current_user.id if params[:article][:user_id].nil?
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :user_id, :price)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= article.user_id %>
  </p>

  <% if !simple %>
    <p>
      <strong>Content:</strong>
      <%= article.content %>
    </p>
  <% end %>

  <p>
    <strong>Price:</strong>
    <%= "$#{article.price}" %>
  </p>


</div>

app/views/articles/_form.html.erb
<div class="container mx-auto mt-8 flex-grow">
  <%= form_with(model: article) do |form| %>
    <% if article.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

        <ul>
          <% article.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title , class: "shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline input-width"%>

    </div>

    <div>
      <%= form.label :content, style: "display: block" %>
      <%= form.text_area :content, class: "shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline input-width" %>
    </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price, min: 0, class: "shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline input-width" %>
  </div>

  <div>
    <%= form.submit style: "cursor: pointer; margin-top: 10px", class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline btn-width"%>
  </div>

<% end %>
</div>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<%# remember to use flex-grow for other pages so that it works with the footer %>
<%# end %>

<div class="container mx-auto mt-8 flex-grow">
  <h1 class="text-4xl font-bold my-2">Articles</h1>
  <div class="my-4 flex justify-between items-center">
    <%= link_to "New article", new_article_path, class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-1 px-2 border border-blue-500 hover:border-transparent rounded btn-width" %>
    <%= form_with(url: articles_path, method: :get, local: true) do |form| %>
      <%= form.label :sort, "Sort by:", class: "mr-2" %>
      <%= form.select :sort, options_for_select([['Likes', 'likes'], ['Latest', 'latest']], session[:sort]), {}, onchange: 'this.form.submit();', class: "w-64 mt-1 pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md" %>
    <% end %>
  </div>
      <div id="articles" class="grid grid-cols-2 sm:grid-cols-1 lg:grid-cols-3 gap-4">
        <% @articles.each do |article| %>
          <% if article.price == 0 || user_signed_in? %>
          <div class="bg-white my-2 p-6 rounded-lg shadow-md overflow-hidden">
          <% cache article do %>
            <%= render article, simple: true %>
          <% end %>
          <p class="mt-2">
            <%# paid = Transaction.find_by(user_id: current_user.id, article_id: article.id) %>
            <% if user_signed_in? && current_user.id != article.user_id && article.price != 0 && !Transaction.find_by(user_id: current_user.id, article_id: article.id) %>
              <%= link_to "Pay", new_article_transaction_path(article), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
            <% else %>
              <%= link_to "Show this article", article, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded height: 40px;" %>
            <% end %>
          </p>
          </div>
          <% end %>
        <% end %>
      </div>
    <div class="flex justify-center items-center space-y-4 py-8">
      <% if user_signed_in? %>
        <%= paginate @articles %>
      <% else %>
        <%= link_to "Login For More", new_user_session_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
      <% end %>
    </div>
</div>

app/views/articles/new.html.erb
<div class="container mx-auto mt-8 flex-grow">
  <h1 class="text-4xl font-bold my-2">New article</h1>

  <%= render "form", article: @article %>

  <br>

  <div>
    <%= link_to "Back to articles", articles_path, class:"btn bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline btn-width" %>
  </div>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<% button_classes = "" %>

<div class="container mx-auto mt-8 flex-grow">
  <%= render @article, simple: false %>

  <div class="space-y-4">
    <p>Likes: <%= @article.likes_count %></p>
    <% if user_signed_in? %>
      <div class="my-2">
        <% if !current_user.likes.exists?(user_id: current_user.id, article_id: @article.id) %>
          <%= button_to like_article_path(@article), method: :post, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded flex items-center" do %>
            <%= image_tag("like_icon.svg", class: "h-5 w-5 mr-2") %>
            <span>Like</span>
          <% end %>
        <% else %>
          <%= button_to "Unlike", unlike_article_path(@article), method: :delete, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
        <% end %>
      </div>
    <% end %>
    <% if user_signed_in? and current_user.id == @article.user_id %>
      <div class="my-2">
        <%= link_to "Edit this article", edit_article_path(@article), class: "bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded btn-width" %>
      </div>
      <div class="my-2">
        <%= button_to "Destroy this article", @article, method: :delete, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded btn-width" %>
      </div>
      <div class="my-2">
        <%= link_to "Back to articles", articles_path, class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded btn-width" %>
      </div>
    <% else %>
      <div class="my-2">
        <%= link_to "Back to articles", articles_path, class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded btn-width" %>
      </div>
    <% end %>
  </div>
</div>

<hr style="border: 1px solid #ddd; margin: 20px 0 0 0;">

<div class="container mx-auto mt-8 flex-grow">
  <div class="container mt-4">
    <h2 class="text-4xl font-bold my-2 text-lg">All Comments</h2>
  </div>
  <ul style="list-style-type: none; padding: 0;">
    <% @comments.each do |comment| %>
      <li style="border-bottom: 1px solid #ddd; padding: 10px; margin: 0;">
        <p>
          <strong>User:</strong>
          <%= comment.user.email %>
        </p>
        <p>
          <strong>Comment:</strong>
          <%= comment.content %>
        </p>
      </li>
    <% end %>
  </ul>
  <div class="my-2">
    <%= link_to "New Comment", new_article_comment_path(@article), class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-1 px-2 border border-blue-500 hover:border-transparent rounded btn-width" %>
  </div>
</div>